name: example
publish_to: "none"
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  http: ^1.3.0
  markdown: ^7.3.0
  signals_core: ^6.0.2
  web: ">=0.4.2 <2.0.0"
  html_web_components:
    path: ../
dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.0.5
  build_web_compilers: ^4.0.0
scripts:
  build: dart run build_runner build -o web:build --release
  serve: dart run build_runner serve web
