name: html_web_components
version: 0.1.0
description: HTML Web Components with pure dart that compile to WASM and JS
homepage: https://github.com/rodydavis/dart-web-components
repository: https://github.com/rodydavis/dart-web-components
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  signals_core: ^6.0.2
  web: ">=0.4.2 <2.0.0"
dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.0.5
  build_web_compilers: ^4.0.0
scripts:
  build: dart run build_runner build -o web:build --release
  serve: dart run build_runner serve web
